name: SriTataDaily
on:
 schedule:
   - cron: "00 21  * * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Daily Flow
      run: |
                       git config --global user.name "Srionline363"
                       git config --global user.email "srionlinesri363@gmail.com"
                       git clone https://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@github.com/Srionline363/srionline363
                       cd srionline363/
                       git pull https://github.com/ForceGT/Tata-Sky-IPTV || echo "No need to update repo"
                       cd code_samples/
                       chmod 755 *
                       sudo apt-get install expect -y
                       ./script.exp
                       git clone https://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@gist.github.com/d8a9f0bc65d8bf9e5380655aaa45ac64
                       rm d8a9f0bc65d8bf9e5380655aaa45ac64/allChannelPlaylist.m3u
                       mv *.m3u d8a9f0bc65d8bf9e5380655aaa45ac64/
                       cd d8a9f0bc65d8bf9e5380655aaa45ac64
                       git add .
                       git commit -m "Playlist has been updated."
                       git push
                       exit

